# Load libraries ----------------------------------------------------------
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(knitr)
library(ggplot2)
library(dplyr)
library(scales)
library(readr)
library(akima)
library(grid)
library(shinyjs)

# Load data ---------------------------------------------------------------
load("rawData/graph31.RData")
load("rawData/graph31_plot.RData")
load("rawData/graph33.RData")
load("rawData/graph33_plot.RData")
load("rawData/graph34.RData")
load("rawData/graph34_plot.RData")
load("rawData/graph35.RData")
load("rawData/graph35_plot.RData")
load("rawData/graph36.RData")
load("rawData/graph36_plot.RData")